# Gradle
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.warning.mode=none
org.gradle.problems.report=false
javaVersion=21
# Mod
modId=mlog
modName=MLog
modDisplayName=MLog
modLicense=GPL-3.0
modVersion=0.1.2
modGroupId=io.github.forgestove
modAuthors=ForgeStove, zhouzhouwu
modCredits=cym, CMS, Mindustry, AnvilCraft
modDisplayUrl=https://modrinth.com/mod/mlog
modIssueUrl=https://github.com/ForgeStove/MLog/issues
modDescription=Mindustry's logic system, rebuilt for Minecraft: a graphical statement canvas, a graphical statement editor, and the instruction set that goes with them.
# Version
mcVersion=1.21.1
# https://maven.neoforged.net/releases/net/neoforged/neoforge/maven-metadata.xml
loaderVersion=21.1.250
parchmentVersion=2024.11.17
createMinVersion=6.0.10
# https://maven.createmod.net:6085/com/simibubi/create/create-1.21.1/maven-metadata.xml
createVersion=6.0.11-300
# https://maven.createmod.net:6085/net/createmod/ponder/ponder-neoforge/maven-metadata.xml
ponderVersion=1.0.87
# https://maven.createmod.net:6085/dev/engine-room/flywheel/flywheel-neoforge-1.21.1/maven-metadata.xml
flywheelVersion=1.0.6-44
# https://mvn.devos.one/snapshots/com/tterrag/registrate/Registrate/maven-metadata.xml
registrateVersion=MC1.21-1.3.0+67
# https://modrinth.com/mod/jade/versions?g=1.21.1&l=neoforge
jadeVersion=15.10.6
mixinAgentVersion=1.1
# Loader
loader=neoforge
loaderCap=NeoForge
