modLoader = "javafml"
loaderVersion = "0"
issueTrackerURL = "https://github.com/ForgeStove/MLog/issues"
license = "MIT"

[[mods]]
modId = "mlog"
version = "1.0.0"
displayName = "MLog"
authors = "ForgeStove"
credits = ""
displayURL = "https://modrinth.com/mod/mlog"
description = '''Logic from Mindusty.'''
logoFile = "icon.png"
logoBlur = false

enumExtensions = "META-INF/enumextensions.json"

[[mixins]]
config = "mlog.mixins.json"

[[dependencies."mlog"]]
modId = "neoforge"
type = "required"
ordering = "NONE"
side = "BOTH"

[[dependencies."mlog"]]
modId = "minecraft"
type = "required"
ordering = "NONE"
side = "BOTH"
